### ISSUE TITLE
Make into a package?

### ISSUE THREAD

**Issue by adwait** [dobios/btor2-opt#1]
Hi Amelia, this is very elegant! Wondering whether you intend to package it up? 
I am using the internal parser/program classes as a library. Thanks!

**Comment by dobios** [comment]
Hi @adwait thanks for using this! 

Yeah sure I can make it a package. 

Are there any particular features of btor2 you're looking to rely on? I only currently support a the features that btormc supports, but could always extend it to support everything if needed.

**Comment by adwait** [comment]
Hi @dobios, thanks, I've fixed minor bugs and refactored it some so it's importable: https://github.com/adwait/btor2opt. I can make a PR

**Comment by dobios** [comment]
Hey @adwait I checked out your fork and it looks really good! Could you make a PR so that I can include your changes when I package this? Thanks!

**Comment by adwait** [comment]
done!

**Comment by dobios** [comment]
Done, should be available at https://pypi.org/project/btor2-opt/  
Install with 
```
pip install btor2-opt
```
